---
project_dir: /opt/keycloak-ha

vm1_ip: "{{ hostvars['vm1']['host_ip'] }}"
vm2_ip: "{{ hostvars['vm2']['host_ip'] }}"
vm3_ip: "{{ hostvars['vm3']['host_ip'] }}"

keycloak_hostname: "http://{{ vip }}"

compose_project_name: keycloak-ha

etcd_initial_cluster: "{{ hostvars['vm1']['etcd_name'] }}=http://{{ hostvars['vm1']['host_ip'] }}:2380,{{ hostvars['vm2']['etcd_name'] }}=http://{{ hostvars['vm2']['host_ip'] }}:2380,{{ hostvars['vm3']['etcd_name'] }}=http://{{ hostvars['vm3']['host_ip'] }}:2380"
etcd_initial_cluster_token: keycloak-etcd
etcd_initial_cluster_state: new

patroni_scope: keycloak_db

keycloak_db: keycloak
keycloak_db_username: keycloak

pg_haproxy_port: 5433
pg_haproxy_stats_port: 7000

keycloak_image: quay.io/keycloak/keycloak:26.4
keycloak_http_port: 8080

keycloak_db_host: 127.0.0.1
keycloak_db_port: 5433

keycloak_haproxy_port: 80
keycloak_haproxy_stats_port: 8404

ucarp_vhid: 100

ucarp_advskew_vm1: "{{ hostvars['vm1']['ucarp_advskew'] }}"
ucarp_advskew_vm2: "{{ hostvars['vm2']['ucarp_advskew'] }}"

ucarp_healthcheck_url: "http://127.0.0.1/realms/master"
ucarp_healthcheck_interval: 5
ucarp_healthcheck_timeout: 3
ucarp_healthcheck_fails: 3
ucarp_healthcheck_success_to_rejoin: 12

supported_debian_releases:
  - bookworm
  - trixie
