---
postgres_password: postgres_pass

replication_username: replicator
replication_password: replicator_pass

keycloak_db_password: keycloak_pass

keycloak_admin: admin
keycloak_admin_password: admin_pass

haproxy_stats_user: admin
haproxy_stats_password: admin123

ucarp_password: keycloak-ha-vip
