[etcd]
vm1 ansible_host=192.168.182.140 ansible_user=keycloak-vm1
vm2 ansible_host=192.168.182.141 ansible_user=keycloak-vm2
vm3 ansible_host=192.168.182.142 ansible_user=keycloak-vm3

[postgres_nodes]
vm1
vm2

[keycloak_nodes]
vm1
vm2

[ucarp_nodes]
vm1
vm2

[all:vars]
ansible_python_interpreter=/usr/bin/python3
